// Ejemplo de cartas a insertar en la tabla "cartas"
const cartas = [
  // COMUNES
  {
    nombre: "Plancha",
    descripcion: "Se mantiene en plancha con buena ejecución.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url:
      "https://<tu-proyecto>.supabase.co/storage/v1/object/public/cartas-diarias/plancha.png",
  },
  {
    nombre: "Carpa",
    descripcion: "Buena posicion de medio cuadrado.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/carpa.png",
  },
  {
    nombre: "Batidora",
    descripcion: "Mantiene hombros secos y buena postura.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/batidora.png",
  },
  {
    nombre: "Vertical",
    descripcion: "Posicion recta, con buena altura.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/vertical.png",
  },
  {
    nombre: "Flexibilidad",
    descripcion: "Gran elasticidad y control corporal.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/flexibilidad.png",
  },
  {
    nombre: "Coordinación",
    descripcion: "Sincroniza movimientos con precisión.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/coordinacion.png",
  },
  {
    nombre: "Sonrisa",
    descripcion: "Mantiene una expresión agradable durante la rutina.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/sonrisa.png",
  },
  {
    nombre: "Vela",
    descripcion: "Mantiene la vela y la pierna seca.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/vela.png",
  },
  {
    nombre: "Pierna de Ballet",
    descripcion:
      "Pierna de abajo seca,la de arriba apunta hacia el techo y esta recta.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/pierna_ballet.png",
  },
  {
    nombre: "Persistencia",
    descripcion: "No se rinde fácilmente durante el entrenamiento.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/persistencia.png",
  },
  {
    nombre: "Bolita",
    descripcion: "Lo mas cerrada posible.",
    tipo: "diaria",
    rareza_base: "comun",
    imagen_url: "/cartas/comun/bolita.png",
  },

  // RARAS
  {
    nombre: "Americana",
    descripcion: "Movimiento  fluido y efectivo de americana.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/americana.png",
  },
  {
    nombre: "Vertical rodilla doblada",
    descripcion: "Realiza medio giro en altura maxima.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/medio_giro.png",
  },
  {
    nombre: "Caballero",
    descripcion: "Realiza giro en altura maxima.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/giro.png",
  },
  {
    nombre: "Barracuda",
    descripcion: "Control total del cuerpo, subida y bajada recta.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/barracuda.png",
  },
  {
    nombre: "Boost",
    descripcion: "Buena elevacion y preparacion.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/boost.png",
  },
  {
    nombre: "Nervios de acero",
    descripcion: "Mantiene la calma y no se altera.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/nervios.png",
  },
  {
    nombre: "Compañerismo",
    descripcion: "Ayuda a sus compañeras sin dejar de hacer sus ejercicios.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/compañerismo.png",
  },
  {
    nombre: "Trabajo en Equipo",
    descripcion: "Se sincroniza perfectamente con compañeras.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/trabajo_equipo.png",
  },
  {
    nombre: "Cola de pez",
    descripcion:
      "Ejecuta la posicion cola de pez, con buena altura , piernas estiradas y la pierna de abajo en horizontal.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/cola_pez.png",
  },
  {
    nombre: "Concentración",
    descripcion: "Mantiene la atención en lo que esta haciendo.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/concentracion.png",
  },
  {
    nombre: "Pierna de ballet doble submarina",
    descripcion: "Buena posicion de piernas.",
    tipo: "diaria",
    rareza_base: "rara",
    imagen_url: "/cartas/rara/pierna_doble_submarina.png",
  },

  // EPICAS
  {
    nombre: "Y",
    descripcion: "Rápido y preciso en todos los movimientos.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/barracuda_tirabuzon.png",
  },
  {
    nombre: "Marsopa",
    descripcion: "Subida de carpa a vertical con las dos piernas.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/marsopa.png",
  },
  {
    nombre: "Boost dos brazos",
    descripcion: "Buena altura con los dos brazos a la vertical.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/estrella.png",
  },
  {
    nombre: " Tirabuzon",
    descripcion: "Giro descendente rapido.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/_tirabuzon.png",
  },
  {
    nombre: "Fuerza",
    descripcion: "Potencia en cada movimiento.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/fuerza.png",
  },
  {
    nombre: "Resistencia",
    descripcion: "Aguanta la coreografia o los ejercicios.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/resistencia.png",
  },
  {
    nombre: "Arte",
    descripcion: "Expresa emociones mediante la rutina.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/arte.png",
  },
  {
    nombre: "Innovación",
    descripcion: "Crea movimientos originales y únicos.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/innovacion.png",
  },
  {
    nombre: "Comportamiento Ejemplar",
    descripcion: "Destaca por disciplina y respeto.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/comportamiento_ejemplar.png",
  },
  {
    nombre: "Nadadora Experta",
    descripcion: "Los cronos no son nada.",
    tipo: "diaria",
    rareza_base: "epica",
    imagen_url: "/cartas/epica/nadadora_experta.png",
  },

  // LEGENDARIAS
  {
    nombre: "Barracuda espagat",
    descripcion: "Altura, flexibilidad y control de giro.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/barracuda_espagat.png",
  },
  {
    nombre: "Pez Espada",
    descripcion: "Movimiento mágico y deslumbrante.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/pez_espada.png",
  },
  {
    nombre: "Arqueado",
    descripcion: "Velocidad y fuerza combinadas.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/marsopa_2_giros.png",
  },
  {
    nombre: "Vertical 1 giro",
    descripcion: "Movimientos hipnóticos y sorprendentes.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/vertical_espagat_vertical.png",
  },
  {
    nombre: "Maestra del Agua",
    descripcion: "Control absoluto sobre cada movimiento.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/maestra_agua.png",
  },
  {
    nombre: "Inspiración",
    descripcion: "Motiva a todas las compañeras con su rutina.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/inspiracion.png",
  },
  {
    nombre: "Líder Legendaria",
    descripcion: "Ejemplo de disciplina y maestría.",
    tipo: "diaria",
    rareza_base: "legendaria",
    imagen_url: "/cartas/legendaria/lider_legendaria.png",
  },
];

export default cartas;
