export const FRASES = [
  "No importa cuántas veces caigas, lo importante es levantarse.",
  "Si no arriesgas nada, no puedes ganar nada. ",
  "El dolor es temporal, el orgullo es para siempre.",
  "El único que puede decidir tu camino eres tú.",
  "No importa si el mundo se opone, tú sigue adelante.",
  "El esfuerzo siempre supera al talento cuando el talento no se esfuerza.",
  "Supera tus limites, aqui y ahora",
  "La fuerza no proviene de ganar, sino de superar tus límites.",
  "A veces, perder es necesario para aprender a ganar.",
  "Si quieres algo, lucha por ello hasta el final.",
  "El verdadero fracaso es rendirse antes de tiempo.",
  "No importa cuán oscuro esté el camino, siempre habrá luz al final.",
  "Cree en ti mismo incluso cuando nadie más lo haga.",
  "El coraje no es no tener miedo, sino seguir adelante a pesar del miedo.",
  "Cada día es una nueva oportunidad para ser mejor.",
  "La vida no se mide por el tiempo que respiras, sino por los momentos que te dejan sin aliento.",
  "Sigue corriendo, aunque tus piernas digan que no puedes más.",
  "El éxito es la suma de pequeños esfuerzos repetidos día tras día.",
  "No existe límite para quien nunca se rinde.",
  "Los sueños no funcionan si tú no trabajas por ellos.",
  "El sacrificio de hoy es la victoria de mañana.",
  "Cuando pierdas, aprende; cuando ganes, mejora.",
  "Incluso si todo parece imposible, nunca dejes de intentar.",
  "Cada cicatriz cuenta la historia de tu esfuerzo.",
  "El futuro pertenece a los que no se rinden.",
  "No hay atajos para llegar a la grandeza.",
  "Si quieres volar, primero aprende a caer.",
  "El límite solo existe en tu mente.",
  "La derrota no es el fin, sino la lección más valiosa.",
  "Nunca subestimes el poder de la determinación.",
  "El futuro no está escrito, depende de ti cambiarlo.",
  "Incluso los errores son pasos hacia el éxito.",
  "No temas al fracaso, teme no intentarlo.",
  "Nunca subestimes el poder de un solo esfuerzo.",
  "Cada práctica te acerca un paso más a tu objetivo.",
  "No importa de dónde vienes, sino a dónde quieres llegar.",
  "Si no luchas por tus sueños, nadie lo hará por ti.",
  "Tus límites solo existen si tú los aceptas.",
  "Nunca dejes de mejorar, incluso cuando creas que eres fuerte.",
];
